"use client"

import { Roboto } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { ClerkProvider } from "@clerk/nextjs";
import { CartContext } from "@/context/CartContext";
import { useState } from "react"



const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ["latin"]
});

// export const metadata = {
//   title: "E-commernce Site",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([])
  return (
    <ClerkProvider>
      <CartContext.Provider value={{ cart, setCart }}>
        <html lang="en">
          <body className={roboto.className}>
            <Navbar />
            {children}
            <Footer />
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>

  );
}
